### Get admin logs
GET http://{{domain}}/admin/auth.admin_log/index
Batoken: {{token}}
Accept: application/json
Content-Type: application/json

### Get admin logs with query parameters
GET http://{{domain}}/admin/auth.admin_log/index?select=true
Batoken: {{token}}
Accept: application/json
Content-Type: application/json
