### 获取菜单列表
GET http://{{domain}}/admin/auth/rule/index
Batoken: {{admin-token}}
Content-Type: application/json

### 添加菜单
POST http://{{domain}}/admin/auth/rule/add
Batoken: {{admin-token}}
Content-Type: application/json

{
  "title": "New Menu",
  "pid": 1,
  "type": "menu",
  "status": 1
}

### 编辑菜单
POST http://{{domain}}/admin/auth/rule/edit?id=1
Batoken: {{admin-token}}
Content-Type: application/json

{
  "title": "Updated Menu",
  "pid": 2,
  "type": "menu",
  "status": 1
}

### 删除菜单
DELETE http://{{domain}}/admin/auth/rule/del
Batoken: {{admin-token}}
Content-Type: application/json

[
  1, 2
]

### 远程select选项
GET http://{{domain}}/admin/auth/rule/select
Batoken: {{admin-token}}
Content-Type: application/json
