<?php

use app\common\services\platform\MenuService;
use think\facade\Db;
use think\migration\Seeder;

/**
 * 平台菜单初始化seeder
 */
class PlatformAdminRuleSeeder extends Seeder
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run(): void
    {
        $this->truncateData();
        $this->initMenuRule();
    }

    protected function initMenuRule(): void
    {
        $menuList = $this->getPlatformMenu();

        Db::transaction(function () use ($menuList) {
            MenuService::menuCreateOrUpdate($menuList, 0, 'platform');
        });
    }

    protected function getPlatformMenu(): array
    {
        return [
            // 1. 控制台
            [
                'type'      => 'menu_dir',
                'title'     => '控制台',
                'name'      => 'dashboard',
                'path'      => 'dashboard',
                'icon'      => 'fa fa-dashboard',
                'menu_type' => 'tab',
                'url'       => '',
                'component' => '/src/views/backend/dashboard.vue',
                'keepalive' => 1,
                'extend'    => 'none',
                'remark'    => 'Remark lang',
                'weigh'     => 999,
                'status'    => 1,
                'sublist'   => [
                    [
                        'type'  => 'button',
                        'title' => '查看',
                        'name'  => 'dashboard/index',
                    ],
                ]
            ],
            // 2. 租户管理
            [
                'type'      => 'menu_dir',
                'title'     => '租户管理',
                'name'      => 'tenant',
                'path'      => 'tenant',
                'icon'      => 'fa fa-group',
                'menu_type' => '',
                'url'       => '',
                'component' => '',
                'keepalive' => 0,
                'extend'    => 'none',
                'remark'    => '',
                'weigh'     => 130,
                'status'    => 1,
                'sublist'   => [
                    [
                        'type'      => 'menu',
                        'title'     => '租户列表',
                        'name'      => 'tenant/tenant',
                        'path'      => 'tenant/tenant',
                        'icon'      => 'fa fa-group',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/tenant/tenant/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 130,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('tenant/tenant', ['index', 'add', 'edit', 'del', 'initData', 'clearData', 'getTenantConfig', 'config', 'exportTenant']),
                    ],
                    [
                        'type'      => 'button',
                        'title'     => '租户管理员',
                        'name'      => 'tenant/admin',
                        'path'      => 'tenant/admin',
                        'icon'      => 'el-icon-UserFilled',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/tenant/admin/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 120,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('tenant/admin'),
                    ],
                    [
                        'type'      => 'button',
                        'title'     => '租户配置',
                        'name'      => 'tenant/config',
                        'path'      => 'tenant/config',
                        'icon'      => 'el-icon-Setting',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/tenant/config/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 120,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('tenant/config'),
                    ],
                    [
                        'type'      => 'menu',
                        'title'     => 'APP版本管理',
                        'name'      => 'tenant/appVersion',
                        'path'      => 'tenant/appVersion',
                        'icon'      => 'el-icon-UserFilled',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/tenant/appVersion/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 99,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('tenant/appVersion'),
                    ],
                ],
            ],
            // 3. 权限管理
            [
                'type'      => 'menu_dir',
                'title'     => '权限管理',
                'name'      => 'auth',
                'path'      => 'auth',
                'icon'      => 'fa fa-group',
                'menu_type' => '',
                'url'       => '',
                'component' => '',
                'keepalive' => 0,
                'extend'    => 'none',
                'remark'    => '',
                'weigh'     => 100,
                'status'    => 1,
                'sublist'   => [
                    [
                        'type'      => 'menu',
                        'title'     => '管理员管理',
                        'name'      => 'auth/admin',
                        'path'      => 'auth/admin',
                        'icon'      => 'el-icon-UserFilled',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/auth/admin/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 98,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('auth/admin'),
                    ],
                    [
                        'type'      => 'menu',
                        'title'     => '角色组管理',
                        'name'      => 'auth/group',
                        'path'      => 'auth/group',
                        'icon'      => 'fa fa-group',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/auth/group/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => 'Remark lang',
                        'weigh'     => 98,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('auth/group'),
                    ],
                    [
                        'type'      => 'menu',
                        'title'     => '菜单规则管理',
                        'name'      => 'auth/rule',
                        'path'      => 'auth/rule',
                        'icon'      => 'el-icon-Grid',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/auth/rule/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 97,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('auth/rule'),
                    ],
                    [
                        'type'      => 'menu',
                        'title'     => '管理员日志管理',
                        'name'      => 'auth/adminLog',
                        'path'      => 'auth/adminLog',
                        'icon'      => 'el-icon-List',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/auth/adminLog/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 96,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('auth/adminLog', ['index']),
                    ],

                ],
            ],

            // 4. 常规管理
            [
                'type'      => 'menu_dir',
                'title'     => '常规管理',
                'name'      => 'routine',
                'path'      => 'routine',
                'icon'      => 'fa fa-cogs',
                'menu_type' => null,
                'url'       => '',
                'component' => '',
                'keepalive' => 0,
                'extend'    => 'none',
                'remark'    => '',
                'weigh'     => 89,
                'status'    => 1,
                'sublist'   => [
                    [
                        'type'      => 'menu',
                        'title'     => '系统配置',
                        'name'      => 'routine/config',
                        'path'      => 'routine/config',
                        'icon'      => 'el-icon-Tools',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/routine/config/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 88,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('routine/config', ['index', 'edit']),
                    ],
                    [
                        'type'      => 'menu',
                        'title'     => '单页管理',
                        'name'      => 'tenant/pages',
                        'path'      => 'tenant/pages',
                        'icon'      => 'el-icon-Collection',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/tenant/pages/index.vue',
                        'keepalive' => 0,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 10,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('tenant/pages', ['index', 'add', 'edit', 'del', 'sortable']),
                    ],
                    [
                        'type'      => 'menu',
                        'title'     => '附件管理',
                        'name'      => 'routine/attachment',
                        'path'      => 'routine/attachment',
                        'icon'      => 'fa fa-folder',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/routine/attachment/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => 'Remark lang',
                        'weigh'     => 87,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('routine/attachment', ['index', 'edit', 'del']),
                    ],
                    [
                        'type'      => 'menu',
                        'title'     => '个人资料',
                        'name'      => 'routine/adminInfo',
                        'path'      => 'routine/adminInfo',
                        'icon'      => 'fa fa-user',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/routine/adminInfo.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 86,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('routine/adminInfo', ['index', 'edit', 'del']),
                    ],
                ],
            ],

            // 5. 短信管理
            [
                'type'      => 'menu_dir',
                'title'     => '短信管理',
                'name'      => 'sms',
                'path'      => 'sms',
                'icon'      => 'el-icon-ChatLineRound',
                'menu_type' => null,
                'url'       => '',
                'component' => '',
                'keepalive' => 0,
                'extend'    => 'none',
                'remark'    => '',
                'weigh'     => 70,
                'status'    => 1,
                'sublist'   => [
                    [
                        'type'      => 'menu',
                        'title'     => '短信配置',
                        'name'      => 'sms/config',
                        'path'      => 'sms/config',
                        'icon'      => 'el-icon-Setting',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/sms/config.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 70,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('sms/config', ['getConfigKey', 'saveConfig']),
                    ],
                    [
                        'type'      => 'menu',
                        'title'     => '模板变量管理',
                        'name'      => 'sms/variable',
                        'path'      => 'sms/variable',
                        'icon'      => 'fa fa-asterisk',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/sms/variable/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 70,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('sms/variable'),
                    ],
                    [
                        'type'      => 'menu',
                        'title'     => '短信模板管理',
                        'name'      => 'sms/template',
                        'path'      => 'sms/template',
                        'icon'      => 'el-icon-Document',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/sms/template/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 70,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('sms/template'),
                    ],
                    [
                        'type'      => 'menu',
                        'title'     => '短信发送记录',
                        'name'      => 'sms/log',
                        'path'      => 'sms/log',
                        'icon'      => 'el-icon-ChatLineSquare',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/sms/log/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 70,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('sms/log'),
                    ],
                ],
            ],

            // 6. 运维管理
            [
                'type'      => 'menu_dir',
                'title'     => '运维管理',
                'name'      => 'devops',
                'path'      => 'devops',
                'icon'      => 'el-icon-BellFilled',
                'menu_type' => null,
                'url'       => '',
                'component' => '',
                'keepalive' => 0,
                'extend'    => 'none',
                'remark'    => '',
                'weigh'     => 70,
                'status'    => 1,
                'sublist'   => [

                    [
                        'type'      => 'menu_dir',
                        'title'     => '数据安全管理',
                        'name'      => 'security',
                        'path'      => 'security',
                        'icon'      => 'fa fa-shield',
                        'menu_type' => null,
                        'url'       => '',
                        'component' => '',
                        'keepalive' => 0,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 84,
                        'status'    => 1,
                        'sublist'   => [
                            [
                                'type'      => 'menu',
                                'title'     => '数据回收站',
                                'name'      => 'security/dataRecycleLog',
                                'path'      => 'security/dataRecycleLog',
                                'icon'      => 'fa fa-database',
                                'menu_type' => 'tab',
                                'url'       => '',
                                'component' => '/src/views/backend/security/dataRecycleLog/index.vue',
                                'keepalive' => 1,
                                'extend'    => 'none',
                                'remark'    => '',
                                'weigh'     => 84,
                                'status'    => 1,
                                'sublist'   => MenuService::getCommonMenuData('security/dataRecycleLog', ['index', 'edit', 'restore', 'info']),
                            ],
                            [
                                'type'      => 'menu',
                                'title'     => '敏感数据修改记录',
                                'name'      => 'security/sensitiveDataLog',
                                'path'      => 'security/sensitiveDataLog',
                                'icon'      => 'fa fa-expeditedssl',
                                'menu_type' => 'tab',
                                'url'       => '',
                                'component' => '/src/views/backend/security/sensitiveDataLog/index.vue',
                                'keepalive' => 1,
                                'extend'    => 'none',
                                'remark'    => '',
                                'weigh'     => 83,
                                'status'    => 1,
                                'sublist'   => MenuService::getCommonMenuData('security/sensitiveDataLog', ['index', 'del', 'rollback', 'info']),
                            ],
                            [
                                'type'      => 'menu',
                                'title'     => '数据回收规则管理',
                                'name'      => 'security/dataRecycle',
                                'path'      => 'security/dataRecycle',
                                'icon'      => 'fa fa-database',
                                'menu_type' => 'tab',
                                'url'       => '',
                                'component' => '/src/views/backend/security/dataRecycle/index.vue',
                                'keepalive' => 1,
                                'extend'    => 'none',
                                'remark'    => '在此定义需要回收的数据，实现数据自动统一回收',
                                'weigh'     => 82,
                                'status'    => 1,
                                'sublist'   => MenuService::getCommonMenuData('security/dataRecycle'),
                            ],
                            [
                                'type'      => 'menu',
                                'title'     => '敏感字段规则管理',
                                'name'      => 'security/sensitiveData',
                                'path'      => 'security/sensitiveData',
                                'icon'      => 'fa fa-expeditedssl',
                                'menu_type' => 'tab',
                                'url'       => '',
                                'component' => '/src/views/backend/security/sensitiveData/index.vue',
                                'keepalive' => 1,
                                'extend'    => 'none',
                                'remark'    => '在此定义需要保护的敏感字段，随后系统将自动监听该字段的修改操作，并提供了敏感字段的修改回滚功能',
                                'weigh'     => 81,
                                'status'    => 1,
                                'sublist'   => MenuService::getCommonMenuData('security/sensitiveData'),
                            ],
                        ],
                    ],
                    [
                        'type'      => 'menu',
                        'title'     => '模块市场',
                        'name'      => 'moduleStore/moduleStore',
                        'path'      => 'moduleStore',
                        'icon'      => 'el-icon-GoodsFilled',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/module/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 86,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('moduleStore/moduleStore', ['index', 'install', 'changeState', 'uninstall', 'update']),
                    ],
                    [
                        'type'      => 'menu',
                        'title'     => 'CRUD代码生成',
                        'name'      => 'crud/crud',
                        'path'      => 'crud/crud',
                        'icon'      => 'fa fa-code',
                        'menu_type' => 'tab',
                        'url'       => '',
                        'component' => '/src/views/backend/crud/index.vue',
                        'keepalive' => 1,
                        'extend'    => 'none',
                        'remark'    => '',
                        'weigh'     => 80,
                        'status'    => 1,
                        'sublist'   => MenuService::getCommonMenuData('crud/crud', ['index', 'generate', 'delete']),
                    ],

                ]
            ],

        ];
    }


    protected function truncateData(): void
    {

        $sql = 'truncate table platform_menu_rule';
        \think\facade\Db::execute($sql);
    }

}
