<?php

use think\migration\Seeder;

class PlatformConfigSeeder extends Seeder
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $this->truncateData();
        $this->initConfigData();
    }


    protected function truncateData()
    {
        $sql = 'truncate table platform_config';
        \think\facade\Db::execute($sql);
    }

    protected function initConfigData()
    {
        $data = [
            [
                'id'        => 1,
                'name'      => 'config_group',
                'group'     => 'basics',
                'title'     => 'Config group',
                'tip'       => '',
                'type'      => 'array',
                'value'     => '[{"key":"basics","value":"Basics"},{"key":"mail","value":"Mail"},{"key":"config_quick_entrance","value":"Config Quick entrance"},{"key":"upload","value":"上传配置"}]',
                'content'   => "",
                'rule'      => 'required',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => -1,
            ],
            [
                'id'        => 2,
                'name'      => 'site_name',
                'group'     => 'basics',
                'title'     => 'Site Name',
                'tip'       => '站点名称',
                'type'      => 'string',
                'value'     => '平台',
                'content'   => "",
                'rule'      => 'required',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 99,
            ],
            [
                'id'        => 3,
                'name'      => 'record_number',
                'group'     => 'basics',
                'title'     => 'Record number',
                'tip'       => '域名备案号',
                'type'      => 'string',
                'value'     => '渝ICP备8888888号-1',
                'content'   => "",
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 0,
            ],
            [
                'id'        => 4,
                'name'      => 'version',
                'group'     => 'basics',
                'title'     => 'Version number',
                'tip'       => '系统版本号',
                'type'      => 'string',
                'value'     => 'v1.0.0',
                'content'   => "",
                'rule'      => 'required',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 0,
            ],
            [
                'id'        => 5,
                'name'      => 'time_zone',
                'group'     => 'basics',
                'title'     => 'time zone',
                'tip'       => '',
                'type'      => 'string',
                'value'     => 'Asia/Shanghai',
                'content'   => "",
                'rule'      => 'required',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 0,
            ],
            [
                'id'        => 6,
                'name'      => 'no_access_ip',
                'group'     => 'basics',
                'title'     => 'No access ip',
                'tip'       => '禁止访问站点的ip列表,一行一个',
                'type'      => 'textarea',
                'value'     => '',
                'content'   => "",
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 0
            ],
            [
                'id'        => 7,
                'name'      => 'smtp_server',
                'group'     => 'mail',
                'title'     => 'smtp server',
                'tip'       => '',
                'type'      => 'string',
                'value'     => 'smtp.qq.com',
                'content'   => "",
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 99
            ],
            [
                'id'        => 8,
                'name'      => 'smtp_port',
                'group'     => 'mail',
                'title'     => 'smtp port',
                'tip'       => '',
                'type'      => 'string',
                'value'     => '465',
                'content'   => "",
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 0
            ],
            [
                'id'        => 9,
                'name'      => 'smtp_user',
                'group'     => 'mail',
                'title'     => 'smtp user',
                'tip'       => '',
                'type'      => 'string',
                'value'     => '',
                'content'   => "",
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 0
            ],
            [
                'id'        => 10,
                'name'      => 'smtp_pass',
                'group'     => 'mail',
                'title'     => 'smtp pass',
                'tip'       => '',
                'type'      => 'string',
                'value'     => '',
                'content'   => "",
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 0
            ],
            [
                'id'        => 11,
                'name'      => 'smtp_verification',
                'group'     => 'mail',
                'title'     => 'smtp verification',
                'tip'       => '',
                'type'      => 'select',
                'value'     => 'SSL',
                'content'   => '{"SSL":"SSL","TLS":"TLS"}',
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 0
            ],
            [
                'id'        => 12,
                'name'      => 'smtp_sender_mail',
                'group'     => 'mail',
                'title'     => 'smtp sender mail',
                'tip'       => '',
                'type'      => 'string',
                'value'     => '',
                'content'   => "",
                'rule'      => 'email',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 0,
            ],
            [
                'id'        => 13,
                'name'      => 'config_quick_entrance',
                'group'     => 'config_quick_entrance',
                'title'     => 'Config Quick entrance',
                'tip'       => '',
                'type'      => 'array',
                'value'     => '[{"key":"数据回收规则配置","value":"/admin/security/dataRecycle"},{"key":"敏感数据规则配置","value":"/admin/security/sensitiveData"}]',
                'content'   => "",
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 0,
            ],
            [
                'id'        => 20,
                'name'      => 'upload_mode',
                'group'     => 'upload',
                'title'     => '存储方式',
                'tip'       => '',
                'type'      => 'select',
                'value'     => 'alioss',
                'content'   => '{"local":"本地磁盘存储","alioss":"阿里云对象存储OSS"}',
                'rule'      => 'required',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 99,
            ],
            [
                'id'        => 21,
                'name'      => 'upload_bucket',
                'group'     => 'upload',
                'title'     => 'Bucket名称',
                'tip'       => '请在阿里云对象存储控制台查询',
                'type'      => 'string',
                'value'     => '',
                'content'   => "",
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 98,
            ],
            [
                'id'        => 22,
                'name'      => 'upload_access_id',
                'group'     => 'upload',
                'title'     => 'AccessKey ID',
                'tip'       => '请在阿里云个人中心查询',
                'type'      => 'string',
                'value'     => '',
                'content'   => "",
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 97,
            ],
            [
                'id'        => 23,
                'name'      => 'upload_secret_key',
                'group'     => 'upload',
                'title'     => 'AccessKey Secret',
                'tip'       => '请在阿里云个人中心查询',
                'type'      => 'string',
                'value'     => '',
                'content'   => "",
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 96,
            ],
            [
                'id'        => 24,
                'name'      => 'upload_url',
                'group'     => 'upload',
                'title'     => '存储区域',
                'tip'       => '请选择存储区域',
                'type'      => 'string',
                'value'     => 'oss-cn-beijing',
                'content'   => '{"oss-cn-hangzhou":"华东1（杭州） oss-cn-hangzhou","oss-cn-shanghai":"华东2（上海） oss-cn-shanghai","oss-cn-nanjing":"华东5（南京本地地域） oss-cn-nanjing","oss-cn-fuzhou":"华东6（福州本地地域） oss-cn-fuzhou","oss-cn-qingdao":"华北1（青岛） oss-cn-qingdao","oss-cn-beijing":"华北2（北京） oss-cn-beijing","oss-cn-zhangjiakou":"华北 3（张家口） oss-cn-zhangjiakou","oss-cn-huhehaote":"华北5（呼和浩特） oss-cn-huhehaote","oss-cn-wulanchabu":"华北6（乌兰察布） oss-cn-wulanchabu","oss-cn-shenzhen":"华南1（深圳） oss-cn-shenzhen","oss-cn-heyuan":"华南2（河源） oss-cn-heyuan","oss-cn-guangzhou":"华南3（广州） oss-cn-guangzhou","oss-cn-chengdu":"西南1（成都） oss-cn-chengdu","oss-cn-hongkong":"中国（香港） oss-cn-hongkong","oss-us-west-1":"美国（硅谷） oss-us-west-1","oss-us-east-1":"美国（弗吉尼亚） oss-us-east-1","oss-ap-northeast-1":"日本（东京） oss-ap-northeast-1","oss-ap-northeast-2":"韩国（首尔） oss-ap-northeast-2","oss-ap-southeast-1":"新加坡 oss-ap-southeast-1","oss-ap-southeast-2":"澳大利亚（悉尼） oss-ap-southeast-2","oss-ap-southeast-3":"马来西亚（吉隆坡） oss-ap-southeast-3","oss-ap-southeast-5":"印度尼西亚（雅加达） oss-ap-southeast-5","oss-ap-southeast-6":"菲律宾（马尼拉） oss-ap-southeast-6","oss-ap-southeast-7":"泰国（曼谷） oss-ap-southeast-7","oss-ap-south-1":"印度（孟买） oss-ap-south-1","oss-eu-central-1":"德国（法兰克福） oss-eu-central-1","oss-eu-west-1":"英国（伦敦） oss-eu-west-1","oss-me-east-1":"阿联酋（迪拜） oss-me-east-1","oss-cn-hzjbp":"华东1金融云 oss-cn-hzjbp","oss-cn-shanghai-finance-1":"华东2金融云 oss-cn-shanghai-finance-1","oss-cn-beijing-finance-1":"华北2金融云 oss-cn-beijing-finance-1","oss-cn-shenzhen-finance-1":"华南1金融云 oss-cn-shenzhen-finance-1","oss-cn-hzfinance":"杭州金融云公网 oss-cn-hzfinance","oss-cn-shanghai-finance-1-pub":"上海金融云公网 oss-cn-shanghai-finance-1-pub","oss-cn-szfinance":"深圳金融云公网 oss-cn-szfinance","oss-cn-beijing-finance-1-pub":"北京金融云公网 oss-cn-beijing-finance-1-pub"}',
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 95,
            ],
            [
                'id'        => 25,
                'name'      => 'upload_cdn_url',
                'group'     => 'upload',
                'title'     => 'CDN地址',
                'tip'       => '（可选）请输入阿里云对象存储的CDN加速域名，以http(s)://开头',
                'type'      => 'string',
                'value'     => '',
                'content'   => "",
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 0,
                'weigh'     => 94,
            ],
            // 消息提醒相关
            [
                'name'      => 'is_remind',
                'group'     => 'remind',
                'title'     => '是否租户过期提醒',
                'tip'       => '',
                'type'      => 'switch',
                'value'     => 1,
                'content'   => "",
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 1,
                'weigh'     => 0,
            ],
            [
                'name'      => 'remind_method',
                'group'     => 'remind',
                'title'     => '提醒方式',
                'tip'       => '',
                'type'      => 'checkbox',
                'value'     => '["1"]',
                'content'   => '{"1":"短信"}',
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 1,
                'weigh'     => 0,
            ],
            [
                'name'      => 'remind_time_period',
                'group'     => 'remind',
                'title'     => '提醒时间段',
                'tip'       => '',
                'type'      => 'checkbox',
                'value'     => '',
                'content'   => json_encode([
                    30 => '提前30天',
                    15 => '提前15天',
                    7  => '提前7天',
                    3  => '提前3天',
                    1  => '提前1天'
                ]),
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 1,
                'weigh'     => 0,
            ],
            [
                'name'      => 'remind_platform_admin',
                'group'     => 'remind',
                'title'     => '提醒平台管理员',
                'tip'       => '手机号逗号分开',
                'type'      => 'string',
                'value'     => '',
                'content'   => '',
                'rule'      => '',
                'extend'    => '',
                'allow_del' => 1,
                'weigh'     => 0,
            ],
        ];

        $table = $this->table('platform_config');
        $table->insert($data)->save();
    }
}
