### Get Attachment Info
GET http://{{domain}}/admin/routine.attachment/index
Batoken: {{tenant-token}}
Content-Type: application/json
Accept: application/json

###

### Del Attachment Info
DELETE http://{{domain}}/admin/routine.attachment/del
Batoken: {{tenant-token}}
Content-Type: application/json
Accept: application/json

[
  1, 2
]