### 查看分组列表
GET http://{{domain}}/admin/tenant/group/index
Content-Type: application/json
Batoken:  {{admin-token}}

{
  "tenant_id": 1
}

### 选择分组
GET http://{{domain}}/admin/tenant/group/select
Content-Type: application/json
Batoken:  {{admin-token}}

{
  "tenant_id": 1
}
