### 查看 DataRecycleLog
GET http://{{domain}}/admin/security/datarecyclelog/index
Content-Type: application/json

{
  "search": [
    {"field": "admin.nickname", "val": "nickname_value"}
  ]
}

### 还原 DataRecycleLog
POST http://{{domain}}/admin/security/datarecyclelog/restore
Content-Type: application/json

{
  "ids": [1, 2, 3]
}

### 详情 DataRecycleLog
GET http://{{domain}}/admin/security/datarecyclelog/info?id=1
Content-Type: application/json
