### Upload File
POST http://{{domain}}/admin/ajax/upload
Batoken: {{token}}
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="file"; filename="example.txt"
Content-Type: text/plain

This is a sample file content.
--boundary--

###

### 获取省市区数据
GET http://{{domain}}/admin/ajax/area
Batoken:  {{token}}
Content-Type: application/json

###

### Get Area List
GET http://{{domain}}/admin/ajax/getAreaList
Batoken: {{token}}
Content-Type: application/json
Query-String: province=some_province&city=some_city&quickSearch=search_term

###

### Build Suffix SVG
GET http://{{domain}}/admin/ajax/buildSuffixSvg
Batoken: {{token}}
Content-Type: application/json
Query-String: suffix=example&background=white

###

### 获取已脱敏的数据库连接配置列表
GET http://{{domain}}/admin/ajax/getDatabaseConnectionList
Batoken: {{token}}
Content-Type: application/json

###

### 获取数据表列表
GET http://{{domain}}/admin/ajax/getTableList
Batoken: {{token}}
Content-Type: application/json
Query-String: connection=your_connection&samePrefix=true&excludeTable[]=table1&excludeTable[]=table2

###

### 获取表主键字段
GET http://{{domain}}/admin/ajax/getTablePk
Batoken: {{token}}
Content-Type: application/json
Query-String: table=your_table&connection=your_connection

###

### Get Table Field List
GET http://{{domain}}/admin/ajax/getTableFieldList
Batoken: {{token}}
Content-Type: application/json
Query-String: table=your_table&clean=true&connection=your_connection

###

### Change Terminal Config
POST http://{{domain}}/admin/ajax/changeTerminalConfig
Batoken: {{token}}
Content-Type: application/json

###

### Clear Cache
POST http://{{domain}}/admin/ajax/clearCache
Batoken: {{token}}
Content-Type: application/json

{
  "type": "tp"
}

###

### 终端
GET http://{{domain}}/admin/ajax/terminal
Batoken: {{token}}
Content-Type: application/json
