### 获取基础配置
GET http://{{domain}}/admin/sms/config/getConfigKey?name=base
Batoken:  {{admin-token}}
Accept: application/json

### 保存基础配置
POST http://{{domain}}/admin/sms/config/saveConfig?type=base
Batoken:  {{admin-token}}
Content-Type: application/json

{
  "timeout": 30,
  "strategy": "order",
  "gateways": ["gateway1", "gateway2"]
}

### 保存网关配置
POST http://{{domain}}/admin/sms/config/saveConfig?type=gateway&name=your_gateway_name
Batoken:  {{admin-token}}
Content-Type: application/json

{
  "key1": "value1",
  "key2": "value2"
}
